language: node_js
node_js:
  - "8"
script:
- npm run docs
- git status
- git diff
- CHANGED_FILES=$(git diff --name-only | grep -v '^package-lock.json/')
- echo $CHANGED_FILES
- echo $CHANGED_FILES | xargs git diff-index --quiet HEAD --
